# Generated by Django 5.1.4 on 2025-01-22 18:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ecomm_store', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='product',
        ),
    ]
