# Generated by Django 5.1.4 on 2025-01-22 18:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ecomm_store', '0002_delete_product'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name_plural': 'Categories'},
        ),
    ]
