# Generated by Django 5.1.4 on 2025-01-22 19:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ecomm_store', '0003_alter_category_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={},
        ),
    ]
