# Generated by Django 5.1.4 on 2025-01-22 19:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecomm_store', '0005_product'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='img_url',
        ),
        migrations.AddField(
            model_name='product',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='products/'),
        ),
    ]
