# Generated by Django 5.1.4 on 2025-01-30 08:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ecomm_store', '0006_remove_product_img_url_product_image'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='category',
            new_name='Categorie',
        ),
    ]
