# Generated by Django 5.1.5 on 2025-01-31 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecomm_store', '0007_rename_category_categorie'),
    ]

    operations = [
        migrations.AddField(
            model_name='categorie',
            name='category_type',
            field=models.CharField(choices=[('men', 'Men'), ('women', 'Women')], default='men', max_length=5),
        ),
        migrations.AlterField(
            model_name='product',
            name='name',
            field=models.CharField(max_length=50),
        ),
    ]
