# Generated by Django 5.1.4 on 2025-02-06 06:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ecomm_store', '0008_categorie_category_type_alter_product_name'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Categorie',
            new_name='Category',
        ),
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name_plural': 'Category'},
        ),
        migrations.AlterModelOptions(
            name='product',
            options={'verbose_name_plural': 'Product'},
        ),
    ]
